// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const config =  {
    API: {
        GraphQL: {
          endpoint: 'https://jojblcmo75arphlgvphtt4jhoe.appsync-api.eu-central-1.amazonaws.com/graphql',
          region: 'eu-central-1',
          defaultAuthMode: 'apiKey',
          apiKey: 'da2-fcgpd3cglffblmewhz7no2hjeu'
        }
    }
};

export default config;